version: '3.8'

services:
  app:
    image: denoland/deno:latest
    volumes:
      - ..:/workspace:cached
      - deno-cache:/home/deno/.cache/deno
    command: sleep infinity
    ports:
      - '8000:8000'

volumes:
  deno-cache:
